Modification of other files to function in the new Default class
- currently hitting an error of;

 File "C:\Users\ThomasMcConkey\Documents\GitHub\qiskit_metal\qiskit_metal\components\base\qubit.py", line 95, in _set_options_con_lines
    self.options.con_lines[name].update(my_options_con_lines)
  File "C:\Users\ThomasMcConkey\Anaconda3\lib\site-packages\addict\addict.py", line 101, in update
    other.update(args[0])
ValueError: dictionary update sequence element #0 has length 1; 2 is required